allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  better-sqlite3: true
  bufferutil: true
  core-js: true
  esbuild: true
  netlify-cli: true
  prisma: true
  protobufjs: true
  sharp: true
  unix-dgram: true

overrides:
  minimist: ^1.2.8
  effect: ^3.20.0
  esbuild: ^0.25.0
  '@tootallnate/once@<3.0.1': '>=3.0.1'
