export const INITIAL_FORM_STATE = {
  title: "",
  category: "",
  jobType: "",
  location: "",
  isRemote: false,
  applicationDeadline: "",
  salaryMin: "",
  salaryMax: "",
  isSalaryNegotiable: false,
  description: "",
  responsibilities: "",
  requirements: "",
  companyName: "",
  companyWebsite: "",
  companySize: "",
  logo: null,
  companyBio: "",
  contactName: "",
  contactEmail: "",
  contactPhone: "",
  aiDescriptionType: "basic",
  aiCustomPrompt: "",
};
