# Alertmanager Configuration for WorkWise SA
# Comprehensive alerting with multiple channels and routing

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@workwise-sa.com'
  smtp_auth_username: 'alerts@workwise-sa.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  
  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
      
    # High severity alerts
    - match:
        severity: high
      receiver: 'high-alerts'
      group_wait: 10s
      repeat_interval: 1h
      
    # Authentication-related alerts
    - match:
        alertname: 'AuthFailureSpike'
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 15m
      
    # Performance alerts
    - match:
        alertname: 'HighResponseTime'
      receiver: 'performance-team'
      group_wait: 10s
      repeat_interval: 1h
      
    # Database alerts
    - match:
        service: 'database'
      receiver: 'database-team'
      group_wait: 10s
      repeat_interval: 2h
      
    # Cache alerts
    - match:
        service: 'cache'
      receiver: 'infrastructure-team'
      group_wait: 15s
      repeat_interval: 2h

# Inhibition rules to prevent alert spam
inhibit_rules:
  # Inhibit high response time alerts when service is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match:
      alertname: 'HighResponseTime'
    equal: ['service']
    
  # Inhibit cache alerts when Redis is down
  - source_match:
      alertname: 'RedisDown'
    target_match:
      alertname: 'LowCacheHitRate'
    equal: ['service']

# Receiver configurations
receivers:
  # Default receiver for low/medium severity alerts
  - name: 'default-receiver'
    email_configs:
      - to: 'team@workwise-sa.com'
        subject: '[WorkWise SA] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
        headers:
          X-Priority: '3'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: 'WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'

  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@workwise-sa.com'
        subject: '[CRITICAL] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT - IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
        headers:
          X-Priority: '1'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        title: '🚨 CRITICAL: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }}'
        details:
          summary: '{{ .Annotations.summary }}'
          description: '{{ .Annotations.description }}'
          severity: '{{ .Labels.severity }}'
          service: '{{ .Labels.service }}'

  # High severity alerts
  - name: 'high-alerts'
    email_configs:
      - to: 'team@workwise-sa.com'
        subject: '[HIGH] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          HIGH PRIORITY ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
        headers:
          X-Priority: '2'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: '⚠️ HIGH: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'

  # Security team alerts
  - name: 'security-team'
    email_configs:
      - to: 'security@workwise-sa.com'
        subject: '[SECURITY] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY ALERT - IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
        headers:
          X-Priority: '1'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security'
        title: '🔒 SECURITY: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_SECURITY_KEY}'
        description: 'Security Alert: {{ .GroupLabels.alertname }}'
        details:
          summary: '{{ .Annotations.summary }}'
          description: '{{ .Annotations.description }}'
          severity: '{{ .Labels.severity }}'
          service: '{{ .Labels.service }}'

  # Performance team alerts
  - name: 'performance-team'
    email_configs:
      - to: 'performance@workwise-sa.com'
        subject: '[PERFORMANCE] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          PERFORMANCE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#performance'
        title: '⚡ PERFORMANCE: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'

  # Database team alerts
  - name: 'database-team'
    email_configs:
      - to: 'database@workwise-sa.com'
        subject: '[DATABASE] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database'
        title: '🗄️ DATABASE: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'

  # Infrastructure team alerts
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@workwise-sa.com'
        subject: '[INFRASTRUCTURE] WorkWise SA Alert: {{ .GroupLabels.alertname }}'
        body: |
          INFRASTRUCTURE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#infrastructure'
        title: '🏗️ INFRASTRUCTURE: WorkWise SA Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'