name: Job Ingestion Pipeline

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      source:
        description: 'Job source to ingest from'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - indeed
          - linkedin
          - manual
      dry_run:
        description: 'Run without actually ingesting (test mode)'
        required: false
        default: false
        type: boolean

  # Run on push to main branch (for testing)
  push:
    branches: [ main ]
    paths:
      - 'scripts/job_ingestion.py'
      - 'netlify/functions/jobsIngest.js'
      - '.github/workflows/job-ingestion.yml'

jobs:
  ingest-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          cd scripts
          pip install -r requirements.txt
          
      - name: Set up environment
        run: |
          echo "NETLIFY_URL=${{ secrets.NETLIFY_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "MANUAL_JOBS_FILE=${{ secrets.MANUAL_JOBS_FILE }}" >> $GITHUB_ENV
          
      - name: Run job ingestion pipeline
        run: |
          cd scripts
          python job_ingestion.py
        env:
          NETLIFY_URL: ${{ secrets.NETLIFY_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          MANUAL_JOBS_FILE: ${{ secrets.MANUAL_JOBS_FILE }}
          
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: job-ingestion-logs
          path: |
            scripts/job_ingestion.log
            scripts/*.log
          retention-days: 7
          
      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#workwise-sa'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Optional: Run tests after ingestion
  test-ingestion:
    runs-on: ubuntu-latest
    needs: ingest-jobs
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install test dependencies
        run: |
          cd scripts
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd scripts
          python -m pytest tests/ -v
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            scripts/test-results.xml
            scripts/coverage.xml
          retention-days: 30
